### ISSUE TITLE
Support for pkcs#1 format

### ISSUE THREAD

**Issue by viecks** [rustls/rcgen#123]
When private key is in pkcs#1 format, rcgen::KeyPair::from_der() will return RcgenError::CouldNotParseKeyPair.
Could we add :
```
        } else if let Ok(rsakp) = RsaKeyPair::from_der(pkcs8) {
            (KeyPairKind::Rsa(rsakp, &signature::RSA_PKCS1_SHA256), &PKCS_RSA_SHA256)
```
in KeyPair's from_raw in order to support pkcs#1 ?

**Comment by est31** [comment]
This looks like a good change. PRs (with tests) are welcome!

**Comment by cpu** [comment]
This is now available with `KeyPair::try_from` for `&[u8]` or `Vec<u8>` when using the `aws-lc-rs` feature.
