### ISSUE TITLE
Splitting up rcgen's lib.rs into smaller modules

### ISSUE THREAD

**Issue by est31** [rustls/rcgen#139]
Suggested by @cpu in #137.

I don't think we should overdo this, but there is certainly potential to split off modularized components from the main lib.rs file:

- [x] Split off oid module: fbd48ccd6ed2a714efde2697214a826d4f0fdc81
- [x] Split off csr module: e137befe39a38a2bdd6a257b08d89c64ebfe1150 
- [x] Split off key_pair module: 59253f50f67c380d3e11c435553de27bf6ba2db7
- [x] Split off sign_algo module: 8b953954011485df496965791acd588692a99f8c
- [x] Split off error module: e39892cf71d615d214ff9d81b01ebf4605ef577b
- [x] Split off crl module: c0344db8c4dfa58257e847f6affc7ad952be482
- [x] Replace `OID_FOO` with `oid::FOO`
- [ ] (for the next breaking release, so probably after the next minor one) redesign the public API to be a little bit more modularized: move csr and crl stuff into own modules in the public API, maybe also the algos?

**Comment by cpu** [comment]
It feels like we're in pretty good shape here. I checked off the OID task, it was accomplished in f2789b3d770a1c6b2391e254faa0e9e76ceea11b

Are there any other tasks folks had in mind for the last bullet or should we consider this done?

**Comment by est31** [comment]
I think we can close this as done. For the last bullet point, if it makes sense we can track it separately.
