### ISSUE TITLE
Rename convergence branch

### ISSUE THREAD

**Issue by cpu** [rustls/rcgen#143]
Let's rename the convergence branch to `main`.

This can be done online with the web UI (https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch) and will retarget extant PRs automatically.

I don't spot anything else in the CI config or elsewhere that would need to be updated.

I can make the change myself, but will hold doing so until there's been a chance for folks to provide input if they'd prefer a different name or think there might be consequences I haven't called out.

**Comment by est31** [comment]
Personally I'm totally fine with `master` as well. But `main` is shorter so if you prefer working with that, I guess it's okay, shrug.

**Comment by djc** [comment]
I prefer `main`, because it carries no cultural baggage and has therefore become the default across most of the repos I use.

**Comment by est31** [comment]
I don't really agree with this trend to drop uses of terms like "blacklist", "master node", etc. But I also don't really care much about it, just as I feel that the new words don't add much value, the old words don't add it either.

IIRC the cargo support for non-`master` default branches works now, so there is no problem with that any more.

So yeah, if it makes you folks happy, we can do the change.

**Comment by djc** [comment]
I kicked this off.
