### ISSUE TITLE
Publish a 0.11.3 release

### ISSUE THREAD

**Issue by cpu** [rustls/rcgen#163]
We should publish a v0.11.3 release to pick up the fixes from https://github.com/rustls/rcgen/pull/162 for builds w/o the optional `pem` feature.

**Comment by est31** [comment]
I will try to do it on the weekend. If I cannot make it, feel free to make and merge a release PR next week.

**Comment by cpu** [comment]
> I will try to do it on the weekend.

Great, thank you :-)

> If I cannot make it, feel free to make and merge a release PR next week.

Do the Rustls maintainers have the required permissions to publish to Cargo?

**Comment by djc** [comment]
> > If I cannot make it, feel free to make and merge a release PR next week.
> 
> Do the Rustls maintainers have the required permissions to publish to Cargo?

Nope, currently only est31 has permission to publish to crates.io.

Probably good to change that?

**Comment by est31** [comment]
I have added a new [rcgen-publish](https://github.com/orgs/rustls/teams/rcgen-publish) team to the rustls org and added it as owner on crates.io.

**Comment by cpu** [comment]
Thanks!
