### ISSUE TITLE
Bump ring dependency to 0.17.0

### ISSUE THREAD

**Issue by grubles** [rustls/rcgen#171]
Hello. I'd like to run some rust code that uses `rcgen` as a dependency on a powerpc64le machine. Recently, `ring` [added support](https://github.com/briansmith/ring/pull/1057) for this architecture in version 0.17.0. 

Is there anything preventing using 0.17.0 instead of 0.16.20?

**Comment by iamjpotts** [comment]
There's an active PR for it: https://github.com/rustls/rcgen/pull/166

**Comment by grubles** [comment]
Ok thanks. I'll close this then.
