### ISSUE TITLE
publish a release with ring 0.17

### ISSUE THREAD

**Issue by hoodie** [rustls/rcgen#198]
Hi there! Do you think it would be possible to make a release that includes the ring 0.17 update?

Ring 0.17 is considered a major release so rustc will include both 0.16 and 0.17 in a binary,
but since ring itself contains C-code this causes linker warnings on some platforms.

I've been trying to harmonize my dependencies to all use the same version of ring, and rcgen is the last one to not have a release with 0.17 yet. If you're holding our due to breaking changes, maybe 948c3b54eae1db242c7966cfa7338001c3928c2f is a good candidate for a 0.11.4.

Thank you

**Comment by cpu** [comment]
:+1: I think it makes sense to start deciding what needs to land before we cut a 0.12 release.
