### ISSUE TITLE
Support for borrowed `RemoteKeyPair`

### ISSUE THREAD

**Issue by corrideat** [rustls/rcgen#211]
Currently, one of the options for a keypair is:

```
Remote(Box<dyn RemoteKeyPair + Send + Sync>),
```

Although workable, it feels like a `RemoteKeyPair` shouldn't be owned and could be borrowed instead. This is useful in some situations where the RemoteKeyPair could be shared or for more control over the workflow.

I have already implemented this, although the downside is that it pollutes the code with mandatory lifetime annotations. I plan to prepare and submit a PR soon with these changes in case there's any interest.

Quick summary of changes:

1. Borrowed RemoteKeyPair
2. Cleaned up `sign` to separate the DER-parts from the signature parts.
3. I guess mostly useful for testing, implemented the `RemoteKeyPair` trait for `KeyPair`, so it's possible to do `KeyPair::from_remote(&key_pair)` (although it's _not_ possible to do `key_pair.as_remote()`).

**Comment by est31** [comment]
As a workaround, you can make a `struct MyKeyPair(Arc<MyOwnedKeyPair>)` and implement `RemoteKeyPair` on that one. Then you can implement `Clone` on `MyKeyPair` without cloning the inner `MyOwnedKeyPair`. I don't think we should be adding lifetime annotations everywhere.

**Comment by corrideat** [comment]
I think the workaround is suitable and therefore I'll close this. Sorry for the delay to respond.
