### ISSUE TITLE
Release new minor release?

### ISSUE THREAD

**Issue by fornwall** [rustls/rcgen#218]
Would be nice to have a minor release with https://github.com/rustls/rcgen/commit/44bb7c76e9e1d69f491e644a0939564734332e06 included, if possible.

**Comment by cpu** [comment]
[rcgen v0.12.1](https://github.com/rustls/rcgen/releases/tag/v0.12.1) is now available with this fix. Thanks for filing an issue.

**Comment by fornwall** [comment]
Thanks a lot!
