### ISSUE TITLE
Support RSA-based sign algorithms

### ISSUE THREAD

**Issue by AJIOB** [rustls/rcgen#229]
For now, this code generates a panic with the text `Cannot generate self-signed certificate: KeyGenerationUnavailable`:
```rust
let mut cert_params = CertificateParams::new(subject_alt_names);
cert_params.alg = &rcgen::PKCS_RSA_SHA256;
let cert = Certificate::from_params(cert_params).expect("Cannot generate self-signed certificate");
```

After searching, I found that note:
https://github.com/rustls/rcgen/blob/3c3e984e11efa4985ca596fe8ba917e6b676fe77/rcgen/src/key_pair.rs#L104-L109

As I search for now, `aws-lc-rs` has RSA signing support from version 1.6.0 via PR aws/aws-lc-rs#315. Full `aws-lc-rs` changelog can be found [here](https://github.com/aws/aws-lc-rs/releases/tag/v1.6.0).

Can you implement the RSA sign algorithm, please? I need this specific certificate generator.

**Comment by djc** [comment]
I am not motivated to implement this myself, but I will review a PR if you submit one.

**Comment by AJIOB** [comment]
@cpu, do you have some time for implementing this one?

**Comment by cpu** [comment]
@AJIOB Looks like est31 beat me to it :-) Support is in progress: https://github.com/rustls/rcgen/pull/230
