### ISSUE TITLE
Generate RSA keys

### ISSUE THREAD

**Issue by kpcyrd** [rustls/rcgen#278]
I'm personally not that keen about RSA, but SAML explicitly requires RSA or DSA.

With the recent rcgen 0.13.0 release it's possible to select a SignatureAlgorithm (yey!) and I was hoping I could now generate RSA keys too, but this is currently not supported, since it's [not implemented in ring](https://github.com/rustls/rcgen/issues/60#issuecomment-880198854).

```rust
// This currently fails
let keypair = KeyPair::generate_for(&PKCS_RSA_SHA256)?;
````

Opening this issue to request this feature, but I also understand if this doesn't have priority. :)

Also note with this api design it's not clear if a 2048bit or 4096bit RSA key should be generated.

Thanks!

**Comment by cpu** [comment]
:wave: hey kpcyrd,

I'm on mobile so my answer isn't as detailed as it should be. RSA key generation is supported w/ the aws-lc-rs backend, but might need better documentation/discoverability. There's an example in the Rustls repo using rcgen to create RSA 2048, 3072 and 4096 key pairs as a ref. point: https://github.com/rustls/rustls/blob/main/rustls/examples/internal/test_ca.rs

**Comment by kpcyrd** [comment]
![image](https://github.com/rustls/rcgen/assets/7763184/c879171a-ea7c-4f5e-ae67-65ba5ff4a805)

Got it to work, thank you very much! :)
