### ISSUE TITLE
remotekeypair functionality

### ISSUE THREAD

**Issue by uglyoldbob** [rustls/rcgen#279]
It seems to me that RemoteKeyPair should allow for signature algorithms not supported by rcgen. For example, I want to use a HSM with RemoteKeyPair to generate RSA signatures.

**Comment by djc** [comment]
Seems reasonable -- what limitations are you running into here?

**Comment by uglyoldbob** [comment]
When I try to implement RemoteKeyPair::algorithm, `rcgen::SignatureAlgorithm::from_oid(&OID_PKCS1_RSA_ENCRYPTION.components()).unwrap()` returns `UnsupportedSignatureAlgorithm`

Here is my definition for `OID_PKCS1_RSA_ENCRYPTION`
```
fn as_oid(s: &'static [u64]) -> Oid {
    Oid::Yasna(yasna::models::ObjectIdentifier::from_slice(s))
}

pub static ref OID_PKCS1_RSA_ENCRYPTION: Oid =
        as_oid(&[1, 2, 840, 113_549, 1, 1, 1]);
```

**Comment by uglyoldbob** [comment]
It looks like I'm just using the wrong oid for rsa signatures.

**Comment by est31** [comment]
@uglyoldbob that API is mainly meant to provide a way to obtain the signature algorithm if you don't know it at compile time yet. If you do know it at compile time, it's better to use [one of the constants](https://docs.rs/rcgen/latest/rcgen/index.html#statics).
