### ISSUE TITLE
unique Id

### ISSUE THREAD

**Issue by adhocinterest** [rustls/rcgen#306]
I would like to use the unique id fields as are optional in the spec, however, they do not appear to be supported by the rcgen api.
Are there plans to include them in rc_gen? They are available fields when parsing using X509_parser (issuer_uid and subject_uid).

For reference, I am using self-signed certs to do mutual auth between parties. To support multiple related devices, each party will have a CA that is also self-signed. However, there does not appear to be a way to include the public key of the CA in the cert for verifying the signature of the CA in the cert. So I was going to include this public key as the Unique Id.

If there is a native way (to the API as well as the spec) that doesn't include external resources to the certificate (i.e. a root store or a network call), I am open to that.

**Comment by djc** [comment]
So, the problem you're trying to solve is, you have multiple disjoint CA certificates and you'd like some peer to be able to distinguish from a given signed end entity certificate to discern which CA was the one that signed it?

**Comment by cpu** [comment]
> I would like to use the unique id fields as are optional in the spec, however, they do not appear to be supported by the rcgen api. Are there plans to include them in rc_gen? 

I would not be in favour of supporting them. RFC 5280 [discourages their use saying](https://www.rfc-editor.org/rfc/rfc5280#section-4.1.2.8):
> This profile RECOMMENDS that names not be reused for different entities and that Internet certificates not make use of unique identifiers.  CAs conforming to this profile MUST NOT generate certificates with unique identifiers

> They are available fields when parsing using X509_parser (issuer_uid and subject_uid).

Side-note: these fields appear so infrequently in meaningful certificates that x509_parser's support [was broken](https://github.com/rusticata/x509-parser/pull/145) until I fixed it for the purpose of linting certificates to reject further use in a context of enforcing 5280 policy. 

> However, there does not appear to be a way to include the public key of the CA in the cert for verifying the signature of the CA in the cert.

It sounds like you're proposing distributing the public key of the root of trust inside of the leaf certificate and then extracting it from the leaf certificate and using it to verify the signature over the leaf? What would prevent an adversary from replacing the public key of the CA in the leaf cert with its own and then recomputing the signature using its own corresponding private key? 

> If there is a native way (to the API as well as the spec) that doesn't include external resources to the certificate (i.e. a root store or a network call), I am open to that.

I believe what you're asking for is fundamentally incompatible with PKI. I think you should relax your requirements or consider a different solution that doesn't involve X.509 certificates.

**Comment by adhocinterest** [comment]
You are welcome to close this with no changes. 

I am going to use X509_cert instead. It's a lot less user friendly, but it's getting the job done.

I do admit that my use case is rather custom. It is for a personal project that is peer to peer and it relies on self-signed certs for the CA. The CA is only for allowing endpoints to determine if two devices are related (created/managed by the same user). If they are related they will have the same CA, otherwise they will not. It seems to me this would not be spoofable without breaking the crypto. It is a very different model than traditional crypto. I can respect whatever decision is made.

**Comment by cpu** [comment]
What you're doing still sounds dangerous to me and I would caution you against continuing down this path. 

For most P2P applications like this I think X.509 and PKI are a bad fit. In your shoes I would look into RFC 7250 raw public keys.

Best of luck,
