### ISSUE TITLE
Add example to demonstrate how to create a CA and a certificate signed with that CA.

### ISSUE THREAD

**Issue by rukai** [rustls/rcgen#79]
Add example to demonstrate how to create a CA and a certificate signed with that CA.

Basically I want to be able to generate the ca.crt/ca.key and redis.crt/redis.key files that this script generates https://github.com/redis/redis/blob/unstable/utils/gen-test-certs.sh#L5+L6
But I cant figure out how to from looking at the API, it seems like it should be possible though?

**Comment by est31** [comment]
@rukai yes, generating both the CA and certificate signed by the CA is possible.

**Comment by est31** [comment]
There is no example, but you can check test code for that setting: https://github.com/est31/rcgen/blob/bab6747b0c3a703112f2fe45f4c2ec144da0de7f/tests/webpki.rs#L212-L230

**Comment by cpu** [comment]
I believe this can be considered resolved thanks to @tbro and https://github.com/rustls/rcgen/pull/174.
