### ISSUE TITLE
API is not very clear about how to sign one `Certificate` with another one.

### ISSUE THREAD

**Issue by vi** [rustls/rcgen#89]
The only mention of signing new certificates I see is `serialize_*_with_signer` functions.

I am expected to serialize, then immediately deserialize certificate even though there is no intention to save it to file or transmit.

Documentation may be more clear about why signing and serialization are one step. I expected there be something like `rcgen::Certificate::from_params_with_signer(params: CertificateParams, ca: &Certificate)`, so I can sign certificate, then serialize it if needed (or use somehow directly).

**Comment by est31** [comment]
PRs are welcome, and also open to discuss solutions.

**Comment by szguoxz** [comment]
This is interesting, are you saying we can't do it yet? I have tried the whole day without success!

**Comment by est31** [comment]
You can sign certificates with another one. The `_from_signer` functions are relevant here. You can grep the tests for uses of that function.
E.g.: https://docs.rs/rcgen/0.10.0/rcgen/struct.Certificate.html#method.serialize_der_with_signer

**Comment by cpu** [comment]
I think the new example from https://github.com/rustls/rcgen/pull/174 and the upcoming CLI tool are probably sufficient to close this. We can revisit if there are other suggestions to make the API clearer.
